name: Bug Report
description: An unexpected problem or behavior in the software or documentation
title: "[Bug]: "
type: 'Bug'
# projects:
# assignees:
body:
  - type: textarea
    id: description
    attributes:
      label: Beschreibe den Fehler
      description: Beschreibe den Fehler, den du gefunden hast.
      placeholder: "Bitte beschreibe den Fehler hier..."
    validations:
      required: true

  - type: textarea
    id: steps_to_reproduce
    attributes:
      label: Schritte zur Reproduktion
      description: Detaillierte Schritte, um das Problem zu reproduzieren.
      placeholder: "Bitte beschreibe die Schritte hier..."
    validations:
      required: false

  - type: textarea
    id: expected
    attributes:
      label: Erwartetes Verhalten
      description: Beschreibe, was du erwartet hast.
      placeholder: "Bitte beschreibe das zu erwartende Verhalten hier ..."
    validations:
      required: true

