name: Improvement
description: Erstellen Sie eine Verbesserungsanfrage.
title: "[Verbesserung]: "
labels: ["verbesserung"]
# projects: 
# assignees:

body:
  - type: markdown
    attributes:
      value: |
        Vielen Dank, dass Sie sich die Zeit nehmen, um diesen Fehlerbericht auszufüllen!
  - type: input
    id: contact
    attributes:
      label: Kontaktdaten
      description: Wie können wir Sie erreichen, wenn wir weitere Informationen benötigen?
      placeholder: z.B. email@example.com
    validations:
      required: false
  - type: textarea
    id: what-happened
    attributes:
      label: Was ist passiert?
      description: Bitte teilen Sie uns auch mit, was Sie erwartet haben.
      placeholder: Sagen Sie uns, was Sie sehen!
      value: "Ein Fehler ist aufgetreten!"
    validations:
      required: true
  - type: dropdown
    id: version
    attributes:
      label: Version
      description: Welche Version unserer Software verwenden Sie?
      options:
        - 1.0.2 (Standard)
        - 1.0.3 (Edge)
      default: 0
    validations:
      required: true
  - type: dropdown
    id: browsers
    attributes:
      label: Auf welchen Browsern tritt das Problem auf?
      multiple: true
      options:
        - Firefox
        - Chrome
        - Safari
        - Microsoft Edge
  - type: textarea
    id: logs
    attributes:
      label: Relevantes Protokollausgabe
      description: Bitte kopieren und fügen Sie relevante Protokollausgaben ein. Diese werden automatisch in Code formatiert, daher sind keine Backticks erforderlich.
      render: shell
  - type: checkboxes
    id: terms
    attributes:
      label: Verhaltenskodex
      description: Durch das Einreichen dieses Problems erklären Sie sich damit einverstanden, unseren [Verhaltenskodex](https://example.com) einzuhalten.
      options:
        - label: Ich stimme zu, den Verhaltenskodex dieses Projekts einzuhalten
          required: true
